name: Playwright Tests ING

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: playwright install --with-deps
      - name: Run tests on ${{ matrix.browser }}
        env:
          PYTHONPATH: .
        run: pytest tests/test_cookie_consent.py -- --mybrowser=firefox --isheaded=false
